version: "3"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD_DB
      MYSQL_DATABASE: $DATABASE_DB
      MYSQL_USER: $USER_DB
      MYSQL_PASSWORD: $PASSWORD_DB
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"
    depends_on:
      - mariadb
    working_dir: /var/www/html/

  # environment:
  #   - APACHE_DOCUMENT_ROOT=/var/www/html/stupid-blog-main
  #command: ["apache2-foreground"]
volumes:
  data:
